apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  storageClassName: standard-class
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /var/data/mysql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: k8s-practice
spec:
  storageClassName: standard-class
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: my-pv
